<?php
// backend/init_db.php
require_once 'config.php';

try {
    $sql = "
    CREATE TABLE IF NOT EXISTS logos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        src TEXT NOT NULL,
        display_type ENUM('image', 'text', 'both') DEFAULT 'image',
        position INT DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS leads (
        id INT AUTO_INCREMENT PRIMARY KEY,
        full_name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        company VARCHAR(255),
        contact_number VARCHAR(100),
        service VARCHAR(255),
        message TEXT,
        status ENUM('new', 'contacted', 'archived') DEFAULT 'new',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS guides (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        description TEXT,
        content LONGTEXT,
        image_url TEXT,
        category VARCHAR(100),
        cta_label VARCHAR(100) DEFAULT 'Download Guide',
        cta_link TEXT,
        feature1 VARCHAR(255),
        feature2 VARCHAR(255),
        feature3 VARCHAR(255),
        feature4 VARCHAR(255),
        stat1_label VARCHAR(100),
        stat1_value VARCHAR(100),
        stat2_label VARCHAR(100),
        stat2_value VARCHAR(100),
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS testimonials (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        role VARCHAR(255),
        company VARCHAR(255),
        content TEXT NOT NULL,
        image_url TEXT,
        category VARCHAR(100),
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS testimonials_focus (
        id INT AUTO_INCREMENT PRIMARY KEY,
        type ENUM('logo', 'video', 'photo') DEFAULT 'logo',
        url TEXT,
        thumbnail_url TEXT,
        label VARCHAR(255),
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS blogs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        excerpt TEXT,
        content LONGTEXT,
        image_url TEXT,
        category VARCHAR(100),
        tags TEXT,
        position INT DEFAULT 0,
        published_at DATE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS case_studies (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        subtitle VARCHAR(255),
        description TEXT,
        client_name VARCHAR(255),
        industry VARCHAR(100),
        challenge TEXT,
        solution TEXT,
        results TEXT,
        image_url TEXT,
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS site_content (
        section VARCHAR(50) PRIMARY KEY,
        content JSON NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS settings (
        `key` VARCHAR(50) PRIMARY KEY,
        `value` TEXT
    );

    CREATE TABLE IF NOT EXISTS newsletter_subscribers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        status ENUM('active', 'unsubscribed') DEFAULT 'active'
    );

    CREATE TABLE IF NOT EXISTS service_content (
        slug       VARCHAR(50) NOT NULL,
        section    VARCHAR(50) NOT NULL,
        content    JSON NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (slug, section)
    );

    -- Insert default logos if table is empty
    INSERT INTO logos (name, src, position) 
    SELECT 'Dish', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Dish_Network_logo.svg', 0
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Dish');

    INSERT INTO logos (name, src, position) 
    SELECT 'Deloitte', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Deloitte.svg', 1
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Deloitte');

    INSERT INTO logos (name, src, position) 
    SELECT 'Pfizer', 'https://upload.wikimedia.org/wikipedia/commons/5/57/Pfizer_%282021%29.svg', 2
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Pfizer');

    INSERT INTO logos (name, src, position) 
    SELECT 'Adobe', 'https://upload.wikimedia.org/wikipedia/commons/a/af/Adobe_Experience_Cloud_logo.svg', 3
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Adobe');

    INSERT INTO logos (name, src, position) 
    SELECT 'American Airlines', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/American_Airlines_logo_2013.svg', 4
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'American Airlines');

    INSERT INTO logos (name, src, position) 
    SELECT 'NBCUniversal', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/NBC_Universal_Logo.svg', 5
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'NBCUniversal');
    ";

    $pdo->exec($sql);
    $sql_testimonials = "
    INSERT INTO testimonials (name, role, company, content, image_url, category, position)
    SELECT 'Sarah Chen', 'Product Manager', 'Stripe', 'The AI workflows implemented by Digi Pexel transformed our support operations. We reduced response times by 70% while improving customer satisfaction scores.', 'https://i.pravatar.cc/150?u=sarah', 'Fintech', 0
    WHERE NOT EXISTS (SELECT 1 FROM testimonials WHERE name = 'Sarah Chen');

    INSERT INTO testimonials (name, role, company, content, image_url, category, position)
    SELECT 'Marcus Rodriguez', 'Founder', 'GrowthLoop', 'We tried building internal AI systems for 6 months with no luck. Digi Pexel delivered a production-ready lead scoring agent in 3 weeks.', 'https://i.pravatar.cc/150?u=marcus', 'SaaS', 1
    WHERE NOT EXISTS (SELECT 1 FROM testimonials WHERE name = 'Marcus Rodriguez');

    INSERT INTO testimonials (name, role, company, content, image_url, category, position)
    SELECT 'Emma Watson', 'Director of Marketing', 'Adobe', 'Their AI SEO strategy is light years ahead. We went from zero AI citations to being the top result for critical industry prompts.', 'https://i.pravatar.cc/150?u=emma', 'Enterprise', 2
    WHERE NOT EXISTS (SELECT 1 FROM testimonials WHERE name = 'Emma Watson');

    ";
    $pdo->exec($sql_testimonials);

    // Seed blog posts (INSERT IGNORE is idempotent — safe to re-run)
    $pdo->exec("INSERT IGNORE INTO blogs (title, slug, eyebrow, subtitle, excerpt, content, image_url, category, tags, author_name, author_role, read_time, status, sections, position, published_at) VALUES
('How AI Automation Eliminates 14 Hours of Manual Work Per Week', 'ai-automation-eliminates-manual-work', 'AI Strategy', 'A practical breakdown of the automation stack that reclaims lost productivity', 'Every knowledge worker loses hours each week on repetitive tasks. Here is how to reclaim that time with autonomous AI workflows.', '', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800', 'AI Strategy', 'automation, AI, workflows, productivity', 'Digi Pexel Team', 'AI Automation Specialists', '8 min read', 'published', '[{\"id\":\"s1\",\"type\":\"overview\",\"title\":\"The Hidden Cost of Manual Operations\",\"content\":\"Research shows knowledge workers spend 40% of their time on low-value repetitive tasks — data entry, status updates, report generation, and tool-switching. That is 16 hours per week per employee that can be reclaimed with properly implemented AI automation.\",\"points\":[\"14 hours/week lost to manual handoffs per employee\",\"73% of repetitive tasks are automatable with current AI tools\",\"Teams with automation report 3x faster output cycles\"]},{\"id\":\"s2\",\"type\":\"challenge\",\"title\":\"Why Most Automation Projects Fail\",\"content\":\"The challenge is not the technology — it is the implementation strategy. Most companies automate tasks in isolation, creating islands of efficiency that do not talk to each other.\",\"points\":[\"Siloed tools with no shared data layer\",\"No error handling or fallback logic\",\"Humans still required for edge cases with no escalation path\"]},{\"id\":\"s3\",\"type\":\"solution\",\"title\":\"The Connected Automation Stack\",\"content\":\"Effective automation operates as a system. Every workflow needs a trigger, a logic layer, error handling, and an observable output. When these components are designed together, automation becomes self-sustaining.\",\"points\":[\"Event-driven triggers that respond to real data changes\",\"LLM decision layer for intelligent routing\",\"Human-in-the-loop checkpoints for high-stakes decisions\",\"Monitoring dashboards with ROI metrics built in\"]},{\"id\":\"s4\",\"type\":\"metrics\",\"title\":\"What Clients Achieve in 90 Days\",\"content\":\"Median outcomes across Digi Pexel clients in their first quarter after deployment.\",\"metrics\":[{\"value\":\"14 hrs\",\"label\":\"Weekly time saved\",\"desc\":\"Per employee on average\"},{\"value\":\"99.2%\",\"label\":\"Workflow uptime\",\"desc\":\"Across all automated pipelines\"},{\"value\":\"3x\",\"label\":\"Output velocity\",\"desc\":\"Faster than pre-automation baseline\"},{\"value\":\"-64%\",\"label\":\"Manual touches\",\"desc\":\"Reduction in human intervention\"}]},{\"id\":\"s5\",\"type\":\"mid_cta\",\"cta_text\":\"Want a free automation audit for your business?\",\"cta_label\":\"Book a Strategy Call\"}]', 0, '2025-03-14')");

    $pdo->exec("INSERT IGNORE INTO blogs (title, slug, eyebrow, subtitle, excerpt, content, image_url, category, tags, author_name, author_role, read_time, status, sections, position, published_at) VALUES
('SEO in the Age of AI: How to Win When LLMs Answer Instead of Google', 'seo-age-of-ai-llm-answers', 'SEO Strategy', 'Generative Engine Optimisation explained for B2B decision makers', 'Search is changing. AI assistants now answer questions directly. Here is how to ensure your brand is the one they cite.', '', 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800', 'SEO', 'SEO, GEO, AI search, LLM, content strategy', 'Digi Pexel Team', 'AI SEO Specialists', '7 min read', 'published', '[{\"id\":\"s1\",\"type\":\"overview\",\"title\":\"The Zero-Click Revolution\",\"content\":\"Over 40% of Google searches now end without a click. AI assistants like ChatGPT, Perplexity, and Gemini answer questions directly from cited sources. If your brand is not one of those sources, you are invisible to an entire generation of buyers.\",\"points\":[\"40%+ of searches end without a click\",\"AI assistants cite 3-5 sources per answer\",\"B2B buyers use AI tools for research before contacting vendors\"]},{\"id\":\"s2\",\"type\":\"challenge\",\"title\":\"Why Traditional SEO Is Not Enough\",\"content\":\"Classic on-page SEO and backlinks still matter, but they do not guarantee AI citation. LLMs are trained on specific datasets and use retrieval-augmented generation to pull live web content. Different signals drive AI visibility.\",\"points\":[\"Keyword density does not drive LLM citations\",\"Backlink authority is a weak signal for AI answers\",\"Structured, entity-rich content outperforms thin pages\"]},{\"id\":\"s3\",\"type\":\"solution\",\"title\":\"Generative Engine Optimisation (GEO)\",\"content\":\"GEO is the practice of optimising content so AI assistants cite your brand in their answers. It combines entity-building, structured content, and authoritative sourcing.\",\"points\":[\"Build topical authority through entity mapping\",\"Use schema markup to signal structured facts\",\"Publish comprehensive pillar content that LLMs can summarise\",\"Earn citations from high-authority sources in your niche\"]},{\"id\":\"s4\",\"type\":\"mid_cta\",\"cta_text\":\"Want an AI visibility audit for your brand?\",\"cta_label\":\"Book a Free Strategy Call\"}]', 1, '2025-04-02')");

    // Seed case studies (INSERT IGNORE is idempotent — safe to re-run)
    $pdo->exec("INSERT IGNORE INTO case_studies (title, slug, eyebrow, subtitle, description, client_name, industry, image_url, hero_cta_label, hero_cta_url, hero_stats, sections, status, position, published_date) VALUES
('How FinFlows Automated 90% of Their Back-Office Operations', 'finflows-back-office-automation', 'Case Study', 'AI-powered workflow automation that eliminated manual processing and cut operational costs by 60%.', 'FinFlows, a fast-growing fintech platform, partnered with Digi Pexel to automate their loan processing, KYC verification, and monthly reporting pipelines.', 'FinFlows Inc.', 'Fintech', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', 'Start Your Project', '/contact-us', '[{\"label\":\"Ops Cost Reduction\",\"value\":\"60%\"},{\"label\":\"Processes Automated\",\"value\":\"40+\"},{\"label\":\"Hours Saved / Week\",\"value\":\"320h\"},{\"label\":\"ROI in 90 Days\",\"value\":\"4.2x\"}]', '[{\"id\":\"c1\",\"type\":\"challenge\",\"title\":\"The Problem: Manual Overload\",\"content\":\"The FinFlows ops team was spending 320 hours per week on manual loan processing, document verification, and compliance reporting. Error rates were high and the team could not scale without proportional headcount growth.\",\"points\":[\"48-hour average KYC verification time\",\"12% error rate on manual data entry\",\"Compliance reporting took 3 full-time employees\"]},{\"id\":\"c2\",\"type\":\"solution\",\"title\":\"The Approach: Autonomous Agent Stack\",\"content\":\"Digi Pexel designed a multi-agent automation system covering identity verification, document parsing, decision routing, and report generation — all orchestrated through a centralised workflow engine.\",\"points\":[\"Custom AI agent for document parsing and entity extraction\",\"Automated KYC decision routing with human escalation path\",\"Real-time compliance report generation via API integration\"]},{\"id\":\"c3\",\"type\":\"metrics\",\"title\":\"Results After 90 Days\",\"content\":\"Measured against pre-deployment baseline.\",\"metrics\":[{\"value\":\"60%\",\"label\":\"Ops cost reduction\",\"desc\":\"Year-one savings\"},{\"value\":\"4 hrs\",\"label\":\"KYC verification\",\"desc\":\"Down from 48 hours\"},{\"value\":\"99.1%\",\"label\":\"Data accuracy\",\"desc\":\"Up from 88%\"},{\"value\":\"4.2x\",\"label\":\"ROI\",\"desc\":\"Within 90 days\"}]}]', 'published', 0, '2025-03-14')");

    $pdo->exec("INSERT IGNORE INTO case_studies (title, slug, eyebrow, subtitle, description, client_name, industry, image_url, hero_cta_label, hero_cta_url, hero_stats, sections, status, position, published_date) VALUES
('How GrowthLoop Scaled LinkedIn Outreach 10x Without Hiring', 'growthloop-linkedin-scale', 'Case Study', 'AI-driven social selling automation that tripled qualified pipeline in 60 days.', 'GrowthLoop, a B2B SaaS company, needed to scale their outbound pipeline without expanding their SDR team. Digi Pexel built an autonomous LinkedIn prospecting and nurture system.', 'GrowthLoop', 'B2B SaaS', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80', 'Start Your Project', '/contact-us', '[{\"label\":\"Pipeline Growth\",\"value\":\"3x\"},{\"label\":\"SDR Hours Saved\",\"value\":\"120/wk\"},{\"label\":\"Response Rate\",\"value\":\"34%\"},{\"label\":\"Time to Deploy\",\"value\":\"3 wks\"}]', '[{\"id\":\"c1\",\"type\":\"challenge\",\"title\":\"The Problem: Outbound at a Ceiling\",\"content\":\"GrowthLoop had a skilled but overloaded SDR team spending 70% of their time on manual prospecting, personalisation, and follow-up. Conversion rates were flat despite headcount growth.\",\"points\":[\"SDRs spending 5+ hours daily on manual list building\",\"Inconsistent follow-up cadence losing warm leads\",\"Personalisation at scale impossible without automation\"]},{\"id\":\"c2\",\"type\":\"solution\",\"title\":\"The Approach: AI Social Selling Engine\",\"content\":\"We built an autonomous LinkedIn prospecting workflow combining AI-powered personalisation, smart sequencing, and intent-based prioritisation — all without violating platform terms.\",\"points\":[\"AI personalisation engine generating custom openers from profile data\",\"Intent-based prioritisation surfacing high-signal accounts daily\",\"Automated multi-touch sequences with human handoff triggers\"]},{\"id\":\"c3\",\"type\":\"metrics\",\"title\":\"Results After 60 Days\",\"content\":\"Measured against the 60-day pre-deployment baseline.\",\"metrics\":[{\"value\":\"3x\",\"label\":\"Qualified pipeline\",\"desc\":\"vs. prior period\"},{\"value\":\"34%\",\"label\":\"Response rate\",\"desc\":\"From 11% baseline\"},{\"value\":\"120 hrs\",\"label\":\"SDR time saved\",\"desc\":\"Per week across team\"},{\"value\":\"3 wks\",\"label\":\"Deployment time\",\"desc\":\"From kickoff to live\"}]}]', 'published', 1, '2025-04-10')");

    // Seed guides (INSERT IGNORE is idempotent — safe to re-run)
    $pdo->exec("INSERT IGNORE INTO guides (title, slug, description, content, image_url, category, cta_label, cta_link, position) VALUES
('The AI Automation Roadmap: A 12-Month Playbook for B2B Teams', 'ai-automation-roadmap-12-month', 'A step-by-step framework for auditing your operations, identifying high-ROI automation opportunities, and building a deployment plan that delivers measurable results within 90 days.', '<h2>Why Most Automation Projects Fail Before They Start</h2><p>Without a clear audit methodology, companies automate the wrong things first — spending budget on low-impact workflows while high-value bottlenecks remain manual. This playbook gives you the framework to avoid that mistake.</p><h2>Phase 1: The Operations Audit (Weeks 1-2)</h2><p>Start by mapping every workflow that involves more than 3 manual steps. Score each workflow on two dimensions: time cost per week and strategic impact. Automate high time-cost, high-impact workflows first.</p><h2>Phase 2: Tool Selection (Weeks 3-4)</h2><p>Match your workflow complexity to the right automation platform. Simple linear flows work well in Zapier or Make. Complex conditional logic with AI decision layers needs n8n or a custom agent framework.</p><h2>Phase 3: Build and Test (Weeks 5-10)</h2><p>Build one workflow at a time. Each workflow must have: a defined trigger, a logic layer, error handling with alerts, and an observable output. Do not move to the next workflow until the current one is stable for 2 weeks.</p><h2>Phase 4: Scale and Optimise (Weeks 11-12)</h2><p>Once your first batch of workflows are stable, introduce monitoring dashboards, set KPI targets, and begin the second round of automation based on updated audit data.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800', 'Strategy', 'Read the Playbook', '#', 0)");

    $pdo->exec("INSERT IGNORE INTO guides (title, slug, description, content, image_url, category, cta_label, cta_link, position) VALUES
('GEO vs SEO: The Complete Guide to Getting Your Brand Cited by AI', 'geo-vs-seo-ai-citation-guide', 'Everything B2B marketing leaders need to know about Generative Engine Optimisation — how AI assistants select citations, what signals matter, and how to build a content strategy that wins in the AI answer era.', '<h2>The Search Landscape Has Changed</h2><p>When a buyer asks ChatGPT or Perplexity about the best automation agency, they receive a direct answer with 3-5 citations. If your brand is not cited, you do not exist in that decision. GEO is the discipline of ensuring you are always one of those citations.</p><h2>How AI Assistants Choose Citations</h2><p>LLMs are trained on web content and augmented with real-time retrieval. They prioritise: authoritative domains with strong topical depth, content that directly answers the query intent, structured markup that makes facts machine-readable, and content cited or linked to by other authoritative sources.</p><h2>The GEO Content Framework</h2><p>Step 1: Build entity authority. Create comprehensive topic clusters around your core service areas. Step 2: Use structured data markup (FAQ, HowTo, Article schemas). Step 3: Publish original research and data — LLMs cite statistics heavily. Step 4: Earn editorial citations from industry publications. Step 5: Monitor your citation rate using AI search tools quarterly.</p><h2>Measuring GEO Success</h2><p>Track: Brand mention rate in AI assistants (test manually monthly), citation share vs. competitors, and inbound traffic from AI-assisted research sessions (identifiable in GA4 by referral source patterns).</p>', 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800', 'SEO', 'Read the Guide', '#', 1)");

    // Seed default settings
    $sql_settings = "
    INSERT INTO settings (`key`, `value`)
    SELECT 'whatsapp_number', ''
    WHERE NOT EXISTS (SELECT 1 FROM settings WHERE `key` = 'whatsapp_number');
    ";
    $pdo->exec($sql_settings);

    // ── service_content seed (INSERT IGNORE so re-runs never overwrite admin edits) ──

    // ai-seo
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'hero', '{\"badge\":\"AI SEO Automation\",\"heroLine1\":\"Stop optimizing for bots.\",\"heroLine2\":\"Start winning AI answers.\",\"heroCopy\":\"We build AI-ready content systems that make your brand the default citation across search assistants, copilots, and LLM-driven research.\",\"ctaPrimary\":\"Book a Strategy Call\",\"pills\":[\"GEO Strategy\",\"Entity Authority\",\"RAG Readiness\"],\"snapshotTitle\":\"Live Visibility Snapshot\",\"snapshotRows\":[\"Model citations: 68%\",\"Entity coverage: 92%\",\"Prompt intent match: 84%\",\"Trust signals: 76%\"],\"statLabel1\":\"Visibility Delta\",\"statValue1\":\"+41%\",\"statLabel2\":\"AI Answer Rate\",\"statValue2\":\"3.2x\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'features', '{\"cards\":[{\"title\":\"GEO Optimization\",\"description\":\"Optimize for Generative Engine Results to ensure your brand is cited by LLMs.\"},{\"title\":\"Entity Authority\",\"description\":\"Map your content to semantic entities to build topical authority that AI understands.\"},{\"title\":\"Automated Content Loop\",\"description\":\"A system that continuously updates content based on AI search trends and intent.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'testimonials', '{\"items\":[{\"quote\":\"Our brand citations in Perplexity and ChatGPT increased by 140% in just two months.\",\"role\":\"CEO\",\"company\":\"Nexus Tech\"},{\"quote\":\"The zero-click search visibility we\'ve gained has been a game-changer for our organic traffic.\",\"role\":\"Marketing Director\",\"company\":\"Aura Media\"}]}')");

    // custom-ai-solutions
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'hero', '{\"badge\":\"Custom AI Solutions\",\"heroLine1\":\"Build AI that fits\",\"heroLine2\":\"your business logic.\",\"heroCopy\":\"We design bespoke AI solutions that integrate with your data, workflows, and proprietary processes. From copilots to autonomous systems, we make AI operational.\",\"ctaPrimary\":\"Plan a Discovery Call\",\"pills\":[\"AI Architecture\",\"Data Pipelines\",\"Workflow Integration\"],\"snapshotTitle\":\"Solution Readiness\",\"snapshotRows\":[\"Use-case clarity: 88%\",\"Data availability: 79%\",\"Model fit score: 86%\",\"Security readiness: 82%\"],\"statLabel1\":\"Delivery speed\",\"statValue1\":\"3x\",\"statLabel2\":\"Ops uplift\",\"statValue2\":\"+45%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'features', '{\"cards\":[{\"title\":\"Custom Agent Design\",\"description\":\"Build autonomous agents specialized in your unique business operations.\"},{\"title\":\"Proprietary RAG\",\"description\":\"Securely connect your private data to LLMs for accurate, context-aware answers.\"},{\"title\":\"Legacy Integration\",\"description\":\"Seamlessly bridge modern AI capabilities with your existing software stack.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'testimonials', '{\"items\":[{\"quote\":\"Digi Pexel built a custom RAG system that cut our document analysis time from hours to seconds.\",\"role\":\"Head of Operations\",\"company\":\"Fortress Law\"},{\"quote\":\"Our proprietary AI agent now handles 80% of our initial client intake with perfect accuracy.\",\"role\":\"Founder\",\"company\":\"ScaleUp\"}]}')");

    // youtube-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'hero', '{\"badge\":\"YouTube Automation\",\"heroLine1\":\"Scale your channel\",\"heroLine2\":\"without the bottlenecks.\",\"heroCopy\":\"We automate scripting, production coordination, publishing, and analytics so your YouTube engine runs every week without burnout.\",\"ctaPrimary\":\"Audit My Channel\",\"pills\":[\"Content Engine\",\"Publishing Ops\",\"Audience Growth\"],\"snapshotTitle\":\"Channel Momentum\",\"snapshotRows\":[\"Upload consistency: 92%\",\"Retention lift: +28%\",\"Topic velocity: 3.4x\",\"Revenue mix: 47%\"],\"statLabel1\":\"Time saved\",\"statValue1\":\"12 hrs/wk\",\"statLabel2\":\"Output lift\",\"statValue2\":\"3x\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'features', '{\"cards\":[{\"title\":\"AI Scripting Engine\",\"description\":\"Generate data-backed scripts that maximize viewer retention and engagement.\"},{\"title\":\"Production Pipeline\",\"description\":\"Automated coordination between editors, designers, and upload managers.\"},{\"title\":\"Topic Velocity\",\"description\":\"Rapidly identify and execute on trending topics before the competition.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'testimonials', '{\"items\":[{\"quote\":\"Closing 8 channels a week used to be impossible. Now we do 12 with a smaller team.\",\"role\":\"Channel Manager\",\"company\":\"MediaFlow\"},{\"quote\":\"The AI scripting tool understands our audience better than we did. Retention is up 35%.\",\"role\":\"Creative Director\",\"company\":\"TubeFoundry\"}]}')");

    // instagram-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'hero', '{\"badge\":\"Instagram Automation\",\"heroLine1\":\"Grow consistently\",\"heroLine2\":\"without manual grind.\",\"heroCopy\":\"Automate content scheduling, engagement workflows, and performance tracking so your brand stays always-on and on-strategy.\",\"ctaPrimary\":\"Get an IG Audit\",\"pills\":[\"Content System\",\"Engagement Ops\",\"Brand Voice\"],\"snapshotTitle\":\"Social Pulse\",\"snapshotRows\":[\"Posting rhythm: 90%\",\"Engagement rate: +22%\",\"DM response time: 3h\",\"Content reuse: 2.6x\"],\"statLabel1\":\"Engagement lift\",\"statValue1\":\"+22%\",\"statLabel2\":\"Time saved\",\"statValue2\":\"9 hrs/wk\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'features', '{\"cards\":[{\"title\":\"Engagement Automator\",\"description\":\"AI-powered DM and comment handling that maintains authentic brand voice.\"},{\"title\":\"Visual Content Hub\",\"description\":\"Centralized system for generating and scheduling Reels, Carousels, and Stories.\"},{\"title\":\"Pattern Analysis\",\"description\":\"Automatically identify what content drives the most follows and sales.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'testimonials', '{\"items\":[{\"quote\":\"Our engagement rate spiked 25% after automating our DM triage system.\",\"role\":\"Social Lead\",\"company\":\"Vibe Marketing\"},{\"quote\":\"We finally have an always-on presence without hiring 3 more community managers.\",\"role\":\"Founder\",\"company\":\"GlowUp\"}]}')");

    // linkedin-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'hero', '{\"badge\":\"LinkedIn Automation\",\"heroLine1\":\"Build authority\",\"heroLine2\":\"at scale.\",\"heroCopy\":\"We automate content publishing, audience engagement, and lead capture so your LinkedIn presence drives pipeline consistently.\",\"ctaPrimary\":\"Book a LinkedIn Audit\",\"pills\":[\"Authority Building\",\"Outbound Assist\",\"Lead Capture\"],\"snapshotTitle\":\"Authority Scorecard\",\"snapshotRows\":[\"Post cadence: 4x\",\"Profile views: +58%\",\"Inbound leads: +36%\",\"Engagement rate: 6.1%\"],\"statLabel1\":\"Lead lift\",\"statValue1\":\"+36%\",\"statLabel2\":\"Authority growth\",\"statValue2\":\"+58%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'features', '{\"cards\":[{\"title\":\"Thought Leadership Ops\",\"description\":\"Scale your professional voice with AI-assisted post generation and scheduling.\"},{\"title\":\"Social Selling Flows\",\"description\":\"Automated lead nurturing and profile visit follow-ups that feel personal.\"},{\"title\":\"Network Growth\",\"description\":\"Strategic connection automation to build a highly targeted industry network.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'testimonials', '{\"items\":[{\"quote\":\"My LinkedIn profile views went from 200 to 5,000 a week. The authority we\'ve built is massive.\",\"role\":\"B2B Founder\",\"company\":\"SaaS Rocket\"},{\"quote\":\"The outreach automation is so subtle—nobody knows it\'s a system, but the results are very real.\",\"role\":\"Sales Director\",\"company\":\"Prime Edge\"}]}')");

    // automation-flows
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'hero', '{\"badge\":\"Automation Flows\",\"heroLine1\":\"Connect your stack\",\"heroLine2\":\"without friction.\",\"heroCopy\":\"We build automation flows that move data and actions across your tools with reliability, observability, and scale.\",\"ctaPrimary\":\"Map My Workflows\",\"pills\":[\"System Orchestration\",\"Data Sync\",\"Reliability\"],\"snapshotTitle\":\"Workflow Health\",\"snapshotRows\":[\"Success rate: 99.2%\",\"Latency: 1.8s\",\"Manual touches: -64%\",\"Error recovery: 92%\"],\"statLabel1\":\"Ops time saved\",\"statValue1\":\"-64%\",\"statLabel2\":\"Flow uptime\",\"statValue2\":\"99.2%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'features', '{\"cards\":[{\"title\":\"Event Orchestration\",\"description\":\"Build complex multi-step flows that trigger based on specific data events.\"},{\"title\":\"Data Synchronization\",\"description\":\"Keep your entire tech stack in sync with zero-latency data transfers.\"},{\"title\":\"Observability Hub\",\"description\":\"Real-time monitoring and alerting for every automated process you run.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'testimonials', '{\"items\":[{\"quote\":\"Our data syncing issues used to cost us $10k a month. Now everything is perfectly in sync.\",\"role\":\"CTO\",\"company\":\"DataFirst\"},{\"quote\":\"The observability dashboards give us total peace of mind for our critical business flows.\",\"role\":\"IT Manager\",\"company\":\"SwiftCore\"}]}')");

    // ai-workflows
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'hero', '{\"badge\":\"AI Workflows\",\"heroLine1\":\"Let AI run\",\"heroLine2\":\"the complex decisions.\",\"heroCopy\":\"We build AI workflows that chain decisions, approvals, and actions across your business with auditability and control.\",\"ctaPrimary\":\"Design My Workflow\",\"pills\":[\"Decision Chains\",\"Human-in-Loop\",\"24/7 Ops\"],\"snapshotTitle\":\"Workflow Intelligence\",\"snapshotRows\":[\"Decision accuracy: 93%\",\"Escalation rate: 7%\",\"Automation coverage: 68%\",\"Cycle time: -41%\"],\"statLabel1\":\"Cycle time\",\"statValue1\":\"-41%\",\"statLabel2\":\"Decision accuracy\",\"statValue2\":\"93%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'features', '{\"cards\":[{\"title\":\"Decision Intelligence\",\"description\":\"AI that reasons through complex scenarios and takes the right action.\"},{\"title\":\"Human-in-Loop QA\",\"description\":\"Smart checkpoints that escalate complex cases to humans while automating the rest.\"},{\"title\":\"Context Chain\",\"description\":\"Maintain business context across multiple automation steps for smarter outcomes.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'testimonials', '{\"items\":[{\"quote\":\"The AI decision chains now handle 70% of our complex claims approvals.\",\"role\":\"Operations Director\",\"company\":\"InsurePlus\"},{\"quote\":\"Bridging human insight with AI reasoning has halved our processing time.\",\"role\":\"Process Architect\",\"company\":\"LogiNext\"}]}')");

    // workflow-creation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'hero', '{\"badge\":\"Workflow Creation\",\"heroLine1\":\"Architect workflows\",\"heroLine2\":\"that never break.\",\"heroCopy\":\"We design dependable business workflows with clear ownership, automation hooks, and measurable performance.\",\"ctaPrimary\":\"Build My Workflow\",\"pills\":[\"Process Design\",\"Automation Ready\",\"Reliability\"],\"snapshotTitle\":\"Workflow Readiness\",\"snapshotRows\":[\"Process clarity: 88%\",\"Automation fit: 74%\",\"Error rate: 6%\",\"Cycle time: -32%\"],\"statLabel1\":\"Cycle time\",\"statValue1\":\"-32%\",\"statLabel2\":\"Automation fit\",\"statValue2\":\"74%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'features', '{\"cards\":[{\"title\":\"System Mapping\",\"description\":\"Detailed blueprints of your business operations to identify automation points.\"},{\"title\":\"Performance Benchmarking\",\"description\":\"Measure every step of your workflow to find and fix hidden bottlenecks.\"},{\"title\":\"Fail-safe Design\",\"description\":\"Workflows built with built-in redundancies and error handling protocols.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'testimonials', '{\"items\":[{\"quote\":\"The blueprints Digi Pexel mapped out revealed bottlenecks we never knew existed.\",\"role\":\"COO\",\"company\":\"Atlas Studio\"},{\"quote\":\"We finally have a scalable workflow architecture that doesn\'t break under pressure.\",\"role\":\"Founder\",\"company\":\"LaunchPoint\"}]}')");

    // accounting-bookkeeping
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'hero', '{\"badge\":\"Accounting Automation\",\"heroLine1\":\"Close books faster\",\"heroLine2\":\"with zero-touch workflows.\",\"heroCopy\":\"We automate reconciliation, reporting, and financial workflows so your team focuses on analysis, not manual cleanup.\",\"ctaPrimary\":\"Book an Accounting Audit\",\"pills\":[\"Reconciliation\",\"Reporting\",\"Compliance\"],\"snapshotTitle\":\"Finance Health\",\"snapshotRows\":[\"Close time: -40%\",\"Reconciliation accuracy: 99%\",\"AP cycle time: -32%\",\"Manual entries: -70%\"],\"statLabel1\":\"Close time\",\"statValue1\":\"-40%\",\"statLabel2\":\"Manual entries\",\"statValue2\":\"-70%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'features', '{\"cards\":[{\"title\":\"Zero-touch Reconciliation\",\"description\":\"Automatically match bank statements with your ledger using AI pattern recognition.\"},{\"title\":\"Real-time P&L\",\"description\":\"Live financial dashboards that update instantly as transactions occur.\"},{\"title\":\"Compliance Guard\",\"description\":\"Automated audits that flag inconsistencies and ensure tax readiness year-round.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'testimonials', '{\"items\":[{\"quote\":\"Closing our month-end now takes 3 days instead of 12. Total transformation.\",\"role\":\"CFO\",\"company\":\"Global Ledger\"},{\"quote\":\"The accuracy and speed of our automated reconciliation is beyond what we expected.\",\"role\":\"Controller\",\"company\":\"FinPath\"}]}')");

    // hiring-recruitment
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'hero', '{\"badge\":\"Hiring Automation\",\"heroLine1\":\"Hire faster\",\"heroLine2\":\"with AI-driven pipelines.\",\"heroCopy\":\"We automate sourcing, screening, and outreach to help you scale hiring without sacrificing quality.\",\"ctaPrimary\":\"Audit My Hiring Flow\",\"pills\":[\"Sourcing\",\"Screening\",\"Candidate Experience\"],\"snapshotTitle\":\"Hiring Velocity\",\"snapshotRows\":[\"Time-to-hire: -35%\",\"Qualified applicants: +48%\",\"Response time: 2h\",\"Offer acceptance: 82%\"],\"statLabel1\":\"Time-to-hire\",\"statValue1\":\"-35%\",\"statLabel2\":\"Qualified leads\",\"statValue2\":\"+48%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'features', '{\"cards\":[{\"title\":\"AI Candidate Sourcing\",\"description\":\"Find top talent across platforms automatically with intelligent search agents.\"},{\"title\":\"Automated Screening\",\"description\":\"Smart interviews and skill assessments that filter for quality at scale.\"},{\"title\":\"Engagement Engine\",\"description\":\"Personalized candidate outreach that maintains high response rates.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'testimonials', '{\"items\":[{\"quote\":\"Our cost-per-hire dropped 40% while our candidate quality actually improved.\",\"role\":\"HR Director\",\"company\":\"ScaleRecruit\"},{\"quote\":\"The AI screening process has saved our team hundreds of hours in top-of-funnel work.\",\"role\":\"Talent Lead\",\"company\":\"Innovate Hub\"}]}')");

    // sales-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'hero', '{\"badge\":\"Sales Automation\",\"heroLine1\":\"Convert faster\",\"heroLine2\":\"with automated follow-up.\",\"heroCopy\":\"We automate lead scoring, nurturing, and pipeline hygiene so sales teams focus on closing, not chasing.\",\"ctaPrimary\":\"Audit My Sales Ops\",\"pills\":[\"Lead Scoring\",\"Follow-up\",\"Pipeline Hygiene\"],\"snapshotTitle\":\"Pipeline Health\",\"snapshotRows\":[\"Response time: -45%\",\"Conversion lift: +29%\",\"Lead scoring: 94%\",\"Stale deals: -38%\"],\"statLabel1\":\"Conversion lift\",\"statValue1\":\"+29%\",\"statLabel2\":\"Response time\",\"statValue2\":\"-45%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'features', '{\"cards\":[{\"title\":\"Predictive Lead Scoring\",\"description\":\"AI that identifies your highest-value leads before you even contact them.\"},{\"title\":\"Multi-channel Follow-up\",\"description\":\"Automated nurturing across Email, LinkedIn, and SMS that never misses a beat.\"},{\"title\":\"CRM Hygiene Bots\",\"description\":\"Autonomous agents that keep your sales data accurate and pipeline clean.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'testimonials', '{\"items\":[{\"quote\":\"Our sales reps are spending 90% of their time on hot leads now. Conversion is at an all-time high.\",\"role\":\"VP Sales\",\"company\":\"CloudScale\"},{\"quote\":\"Automating our follow-up sequences has ensured no lead ever falls through the cracks again.\",\"role\":\"Founder\",\"company\":\"Apex Systems\"}]}')");

    echo "Database initialized successfully.";
} catch (PDOException $e) {
    die("DB Init Error: " . $e->getMessage());
}
