<?php
// backend/init_db.php
require_once 'config.php';

try {
    $sql = "
    CREATE TABLE IF NOT EXISTS logos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        src TEXT NOT NULL,
        display_type ENUM('image', 'text', 'both') DEFAULT 'image',
        position INT DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS leads (
        id INT AUTO_INCREMENT PRIMARY KEY,
        full_name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        company VARCHAR(255),
        contact_number VARCHAR(100),
        service VARCHAR(255),
        message TEXT,
        status ENUM('new', 'contacted', 'archived') DEFAULT 'new',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS guides (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        description TEXT,
        content LONGTEXT,
        image_url TEXT,
        category VARCHAR(100),
        cta_label VARCHAR(100) DEFAULT 'Download Guide',
        cta_link TEXT,
        feature1 VARCHAR(255),
        feature2 VARCHAR(255),
        feature3 VARCHAR(255),
        feature4 VARCHAR(255),
        stat1_label VARCHAR(100),
        stat1_value VARCHAR(100),
        stat2_label VARCHAR(100),
        stat2_value VARCHAR(100),
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS testimonials (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        role VARCHAR(255),
        company VARCHAR(255),
        content TEXT NOT NULL,
        image_url TEXT,
        category VARCHAR(100),
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS testimonials_focus (
        id INT AUTO_INCREMENT PRIMARY KEY,
        type ENUM('logo', 'video', 'photo') DEFAULT 'logo',
        url TEXT,
        thumbnail_url TEXT,
        label VARCHAR(255),
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS blogs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        excerpt TEXT,
        content LONGTEXT,
        image_url TEXT,
        category VARCHAR(100),
        tags TEXT,
        position INT DEFAULT 0,
        published_at DATE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS case_studies (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        subtitle VARCHAR(255),
        description TEXT,
        client_name VARCHAR(255),
        industry VARCHAR(100),
        challenge TEXT,
        solution TEXT,
        results TEXT,
        image_url TEXT,
        position INT DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS site_content (
        section VARCHAR(50) PRIMARY KEY,
        content JSON NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS settings (
        `key` VARCHAR(50) PRIMARY KEY,
        `value` TEXT
    );

    CREATE TABLE IF NOT EXISTS newsletter_subscribers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        status ENUM('active', 'unsubscribed') DEFAULT 'active'
    );

    CREATE TABLE IF NOT EXISTS service_content (
        slug       VARCHAR(50) NOT NULL,
        section    VARCHAR(50) NOT NULL,
        content    JSON NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (slug, section)
    );

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        designation VARCHAR(255),
        login_id VARCHAR(100) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS analytics_codes (
        id INT AUTO_INCREMENT PRIMARY KEY,
        code_key VARCHAR(50) UNIQUE NOT NULL,
        code_value LONGTEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS banners (
        id INT AUTO_INCREMENT PRIMARY KEY,
        config_key VARCHAR(50) UNIQUE NOT NULL,
        config_value LONGTEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS seo_meta (
        page_key VARCHAR(100) PRIMARY KEY,
        seo_title VARCHAR(255),
        meta_description TEXT,
        og_image TEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    -- Insert default logos if table is empty (AI/automation tech partners)
    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Zapier', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Zapier_logo.svg', 'image', 0
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Zapier');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'HubSpot', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/HubSpot_Logo.svg', 'image', 1
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'HubSpot');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Salesforce', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg', 'image', 2
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Salesforce');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Google Ads', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Google_Ads_logo.svg', 'image', 3
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Google Ads');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Meta', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg', 'image', 4
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Meta');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Slack', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Slack_Technologies_Logo.svg', 'image', 5
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Slack');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'OpenAI', '', 'text', 6
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'OpenAI');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Anthropic', '', 'text', 7
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Anthropic');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'n8n', '', 'text', 8
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'n8n');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Microsoft', '', 'text', 9
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Microsoft');

    INSERT INTO logos (name, src, display_type, position)
    SELECT 'Make', '', 'text', 10
    WHERE NOT EXISTS (SELECT 1 FROM logos WHERE name = 'Make');
    ";

    $pdo->exec($sql);

    // Seed default analytics_codes rows
    $pdo->exec("INSERT INTO analytics_codes (code_key, code_value) SELECT 'google_analytics', '' WHERE NOT EXISTS (SELECT 1 FROM analytics_codes WHERE code_key = 'google_analytics')");
    $pdo->exec("INSERT INTO analytics_codes (code_key, code_value) SELECT 'search_console', '' WHERE NOT EXISTS (SELECT 1 FROM analytics_codes WHERE code_key = 'search_console')");
    $pdo->exec("INSERT INTO analytics_codes (code_key, code_value) SELECT 'custom_head_scripts', '' WHERE NOT EXISTS (SELECT 1 FROM analytics_codes WHERE code_key = 'custom_head_scripts')");

    // Seed default banners config
    $pdo->exec("INSERT INTO banners (config_key, config_value) SELECT 'banner', '{\"enabled\":false,\"text\":\"AI automation audit slots open for next week.\",\"ctaLabel\":\"Book a Call\",\"ctaLink\":\"/contact-us\",\"bgColor\":\"#2563EB\"}' WHERE NOT EXISTS (SELECT 1 FROM banners WHERE config_key = 'banner')");
    $pdo->exec("INSERT INTO banners (config_key, config_value) SELECT 'popup', '{\"enabled\":false,\"title\":\"Ready to automate your ops?\",\"body\":\"Get a 20-minute discovery call and a quick automation roadmap.\",\"ctaLabel\":\"Schedule a Call\",\"ctaLink\":\"/contact-us\",\"delayMs\":5000}' WHERE NOT EXISTS (SELECT 1 FROM banners WHERE config_key = 'popup')");
    $pdo->exec("INSERT INTO banners (config_key, config_value) SELECT 'exit_popup', '{\"enabled\":false,\"title\":\"Before you go\",\"body\":\"Want a quick audit checklist? We will send it in minutes.\",\"ctaLabel\":\"Get the Checklist\",\"ctaLink\":\"/contact-us\"}' WHERE NOT EXISTS (SELECT 1 FROM banners WHERE config_key = 'exit_popup')");

    // Seed default admin passcode in settings table (per USR-02 — login page reads this instead of hardcoding)
    // Value is the plain passcode string. The login page compares user input against this value directly.
    // Admin can update it via Settings panel → save_all_settings action.
    $pdo->exec("INSERT INTO settings (`key`, `value`) VALUES ('admin_passcode', 'Vinay@12345') ON DUPLICATE KEY UPDATE `value` = 'Vinay@12345'");

    // Seed admin user profile
    $adminPasswordHash = password_hash('Vinay@12345', PASSWORD_DEFAULT);
    $stmt = $pdo->prepare("INSERT INTO users (name, designation, login_id, password_hash) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE name = VALUES(name), designation = VALUES(designation), password_hash = VALUES(password_hash)");
    $stmt->execute(['Vinay', 'Founder', 'info@digipexel.com', $adminPasswordHash]);

    // Seed calendly_url in settings (empty default — admin sets their Calendly URL)
    $pdo->exec("INSERT INTO settings (`key`, `value`) SELECT 'calendly_url', '' WHERE NOT EXISTS (SELECT 1 FROM settings WHERE `key` = 'calendly_url')");

    // ALTER TABLE to add new testimonials columns (MySQL silently ignores if column already exists)
    $sql_alter = "
    ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS star_rating TINYINT DEFAULT 5;
    ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS video_url TEXT;
    ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS logo_url TEXT;
    ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS display_context VARCHAR(100) DEFAULT 'homepage,testimonials-page';
    ";
    $pdo->exec($sql_alter);

    // Seed canonical testimonials list (all demo data — reset to match local-db.json)
    $pdo->exec("TRUNCATE TABLE testimonials");
    $pdo->exec("INSERT INTO testimonials (id, name, role, company, content, image_url, category, star_rating, video_url, logo_url, display_context, position) VALUES
(1,'Aarav Mehta','COO','Lumina Health','Digi Pexel replaced manual handoffs with AI workflows. Our operations now run in half the time with clear ownership.','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150','Healthcare',5,'','','homepage,testimonials-page',0),
(2,'Priya Nair','Head of Ops','Arrow Logistics','The automation system removed our QA bottleneck. We ship faster and miss fewer deadlines.','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150','Logistics',5,'','','homepage,testimonials-page',1),
(3,'Kabir Singh','VP Growth','Northbridge SaaS','AI-driven lead workflows turned our response time from hours to minutes. Pipeline quality improved immediately.','https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150','SaaS',5,'','','homepage,testimonials-page',2),
(4,'Neha Joshi','Director','FinOps Hub','Reconciliation workflows now run nightly without human intervention. We trust the numbers every morning.','https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150','Finance',5,'','','homepage,testimonials-page',3),
(5,'Zara Sheikh','Product Lead','CloudNorth','The AI workflows reduced escalation volume by 60%. Our support team focuses on high-value cases now.','https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150','SaaS',5,'','','homepage,testimonials-page',4),
(6,'Rahul Verma','Head of RevOps','Signalstack','We finally have a clean pipeline and predictable follow-up. The automation stack just works.','https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150','SaaS',5,'','','homepage,testimonials-page',5),
(7,'Anika Roy','Operations Manager','Crest Labs','Our onboarding workflows went from chaotic to repeatable. New hires ramp in days, not weeks.','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=150','Healthcare',5,'','','homepage,testimonials-page',6),
(8,'Vikram Patel','CEO','Atlas Retail','Digi Pexel delivered a complete automation roadmap and executed it on time. The results are visible weekly.','https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150','Retail',5,'','','homepage,testimonials-page',7),
(9,'Amit Saxena','CEO','TechFlow','The automation workflows implemented by Digi Pexel save our team dozens of hours every week.','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150','Technology',5,'','','homepage,testimonials-page',8),
(10,'Sarah Chen','Product Manager','Stripe','The AI workflows implemented by Digi Pexel transformed our support operations. We reduced response times by 70% while improving customer satisfaction scores.','https://i.pravatar.cc/150?u=sarah','Fintech',5,'','','testimonials-page',9),
(11,'Marcus Rodriguez','Founder','GrowthLoop','We tried building internal AI systems for 6 months with no luck. Digi Pexel delivered a production-ready lead scoring agent in 3 weeks.','https://i.pravatar.cc/150?u=marcus','SaaS',5,'','','testimonials-page',10),
(12,'Emma Watson','Director of Marketing','Adobe','Their AI SEO strategy is light years ahead. We went from zero AI citations to being the top result for critical industry prompts.','https://i.pravatar.cc/150?u=emma','Enterprise',5,'','','testimonials-page',11),
(13,'David Miller','COO','NexGen Logistics','Automating our route optimization with AI Agents has cut fuel costs by 18% and saved countless manual planning hours.','https://i.pravatar.cc/150?u=david','Logistics',5,'','','testimonials-page',12),
(14,'Lisa Wong','Head of Success','ScaleFlow','Digi Pexel didn\'t just give us tools; they gave us a complete automation architecture that scales as we grow.','https://i.pravatar.cc/150?u=lisa','Technology',5,'','','testimonials-page',13),
(15,'James Anderson','Managing Director','Apex Capital','Zero-touch accounting workflows have revolutionized our month-end close. No more manual data entry errors.','https://i.pravatar.cc/150?u=james','Finance',5,'','','testimonials-page',14),
(16,'Sophie Bennett','CTO','DataVise','The reliability of the agents Digi Pexel built is unprecedented. We\'ve had zero downtime in 6 months of operation.','https://i.pravatar.cc/150?u=sophie','Cloud',5,'','','testimonials-page',15),
(17,'Thomas Wright','VP Marketing','Vividly','Our content production quadrupled without adding a single head to the team. The AI coordination is seamless.','https://i.pravatar.cc/150?u=thomas','Marketing',5,'','','testimonials-page',16),
(18,'Elena Petrova','Strategy Lead','GlobalNet','Digi Pexel is the only agency we\'ve found that actually understands how to make LLMs safe for enterprise data.','https://i.pravatar.cc/150?u=elena','Security',5,'','','testimonials-page',17)
");

    // Seed blog posts (INSERT IGNORE is idempotent — safe to re-run)
    $pdo->exec("INSERT IGNORE INTO blogs (title, slug, eyebrow, subtitle, excerpt, content, image_url, category, tags, author_name, author_role, read_time, status, sections, position, published_at) VALUES
('How AI Automation Eliminates 14 Hours of Manual Work Per Week', 'ai-automation-eliminates-manual-work', 'AI Strategy', 'A practical breakdown of the automation stack that reclaims lost productivity', 'Every knowledge worker loses hours each week on repetitive tasks. Here is how to reclaim that time with autonomous AI workflows.', '', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800', 'AI Strategy', 'automation, AI, workflows, productivity', 'Digi Pexel Team', 'AI Automation Specialists', '8 min read', 'published', '[{\"id\":\"s1\",\"type\":\"overview\",\"title\":\"The Hidden Cost of Manual Operations\",\"content\":\"Research shows knowledge workers spend 40% of their time on low-value repetitive tasks — data entry, status updates, report generation, and tool-switching. That is 16 hours per week per employee that can be reclaimed with properly implemented AI automation.\",\"points\":[\"14 hours/week lost to manual handoffs per employee\",\"73% of repetitive tasks are automatable with current AI tools\",\"Teams with automation report 3x faster output cycles\"]},{\"id\":\"s2\",\"type\":\"challenge\",\"title\":\"Why Most Automation Projects Fail\",\"content\":\"The challenge is not the technology — it is the implementation strategy. Most companies automate tasks in isolation, creating islands of efficiency that do not talk to each other.\",\"points\":[\"Siloed tools with no shared data layer\",\"No error handling or fallback logic\",\"Humans still required for edge cases with no escalation path\"]},{\"id\":\"s3\",\"type\":\"solution\",\"title\":\"The Connected Automation Stack\",\"content\":\"Effective automation operates as a system. Every workflow needs a trigger, a logic layer, error handling, and an observable output. When these components are designed together, automation becomes self-sustaining.\",\"points\":[\"Event-driven triggers that respond to real data changes\",\"LLM decision layer for intelligent routing\",\"Human-in-the-loop checkpoints for high-stakes decisions\",\"Monitoring dashboards with ROI metrics built in\"]},{\"id\":\"s4\",\"type\":\"metrics\",\"title\":\"What Clients Achieve in 90 Days\",\"content\":\"Median outcomes across Digi Pexel clients in their first quarter after deployment.\",\"metrics\":[{\"value\":\"14 hrs\",\"label\":\"Weekly time saved\",\"desc\":\"Per employee on average\"},{\"value\":\"99.2%\",\"label\":\"Workflow uptime\",\"desc\":\"Across all automated pipelines\"},{\"value\":\"3x\",\"label\":\"Output velocity\",\"desc\":\"Faster than pre-automation baseline\"},{\"value\":\"-64%\",\"label\":\"Manual touches\",\"desc\":\"Reduction in human intervention\"}]},{\"id\":\"s5\",\"type\":\"mid_cta\",\"cta_text\":\"Want a free automation audit for your business?\",\"cta_label\":\"Book a Strategy Call\"}]', 0, '2025-03-14')");

    $pdo->exec("INSERT IGNORE INTO blogs (title, slug, eyebrow, subtitle, excerpt, content, image_url, category, tags, author_name, author_role, read_time, status, sections, position, published_at) VALUES
('SEO in the Age of AI: How to Win When LLMs Answer Instead of Google', 'seo-age-of-ai-llm-answers', 'SEO Strategy', 'Generative Engine Optimisation explained for B2B decision makers', 'Search is changing. AI assistants now answer questions directly. Here is how to ensure your brand is the one they cite.', '', 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800', 'SEO', 'SEO, GEO, AI search, LLM, content strategy', 'Digi Pexel Team', 'AI SEO Specialists', '7 min read', 'published', '[{\"id\":\"s1\",\"type\":\"overview\",\"title\":\"The Zero-Click Revolution\",\"content\":\"Over 40% of Google searches now end without a click. AI assistants like ChatGPT, Perplexity, and Gemini answer questions directly from cited sources. If your brand is not one of those sources, you are invisible to an entire generation of buyers.\",\"points\":[\"40%+ of searches end without a click\",\"AI assistants cite 3-5 sources per answer\",\"B2B buyers use AI tools for research before contacting vendors\"]},{\"id\":\"s2\",\"type\":\"challenge\",\"title\":\"Why Traditional SEO Is Not Enough\",\"content\":\"Classic on-page SEO and backlinks still matter, but they do not guarantee AI citation. LLMs are trained on specific datasets and use retrieval-augmented generation to pull live web content. Different signals drive AI visibility.\",\"points\":[\"Keyword density does not drive LLM citations\",\"Backlink authority is a weak signal for AI answers\",\"Structured, entity-rich content outperforms thin pages\"]},{\"id\":\"s3\",\"type\":\"solution\",\"title\":\"Generative Engine Optimisation (GEO)\",\"content\":\"GEO is the practice of optimising content so AI assistants cite your brand in their answers. It combines entity-building, structured content, and authoritative sourcing.\",\"points\":[\"Build topical authority through entity mapping\",\"Use schema markup to signal structured facts\",\"Publish comprehensive pillar content that LLMs can summarise\",\"Earn citations from high-authority sources in your niche\"]},{\"id\":\"s4\",\"type\":\"mid_cta\",\"cta_text\":\"Want an AI visibility audit for your brand?\",\"cta_label\":\"Book a Free Strategy Call\"}]', 1, '2025-04-02')");

    $pdo->exec("INSERT IGNORE INTO blogs (title, slug, eyebrow, subtitle, excerpt, content, image_url, category, tags, author_name, author_role, read_time, status, sections, position, published_at) VALUES
('How to Evaluate an AI Automation Agency: 8 Questions Every COO Must Ask', 'evaluate-ai-automation-agency-coo-guide', 'Buyer Guide', 'A no-fluff framework for vetting vendors before you sign a contract', 'Most agencies overpromise and underdeliver on AI. Here is exactly what to ask before committing budget.', '', 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&q=80&w=800', 'Strategy', 'AI agency, vendor selection, COO, automation ROI, due diligence', 'Digi Pexel Team', 'AI Strategy Consultants', '6 min read', 'published', '[{\"id\":\"s1\",\"type\":\"overview\",\"title\":\"Why Most AI Projects Fail at the Vendor Stage\",\"content\":\"Gartner reports that over 80% of AI projects fail to reach production. The leading cause is not bad technology — it is a mismatch between vendor capability and client operational reality. The right questions surface this mismatch before you spend a dollar.\",\"points\":[\"80% of AI projects fail before production launch\",\"Vendor overpromising is the leading risk factor\",\"Scoping misalignment costs 3-6 months of wasted sprint time\"]},{\"id\":\"s2\",\"type\":\"challenge\",\"title\":\"The 8 Questions That Separate Real Vendors From Pretenders\",\"content\":\"Ask these in your first discovery call. Weak vendors will deflect, add caveats, or give template answers. Strong vendors will answer with specifics.\",\"points\":[\"Q1: Show me a workflow you built for a company in my industry.\",\"Q2: What does your error handling and monitoring architecture look like?\",\"Q3: How do you handle a workflow that breaks at 2am on a Sunday?\",\"Q4: What is your standard SLA for uptime on production automations?\",\"Q5: Can you walk me through your data security and access control model?\",\"Q6: What does your off-boarding process look like if we end the engagement?\",\"Q7: How do you measure ROI, and at what cadence do you report it?\",\"Q8: Who on your team will own our account day-to-day?\"]},{\"id\":\"s3\",\"type\":\"solution\",\"title\":\"Green Flags and Red Flags to Watch For\",\"content\":\"A competent AI automation partner will proactively address risks you have not asked about yet. They will also push back on unrealistic timelines and scope creep rather than just saying yes.\",\"points\":[\"Green flag: they ask about your existing tech stack before proposing anything\",\"Green flag: they reference real failure cases and how they resolved them\",\"Red flag: no mention of monitoring, alerting, or fallback logic\",\"Red flag: vague answers about team structure and escalation paths\"]},{\"id\":\"s4\",\"type\":\"mid_cta\",\"cta_text\":\"Want to see how Digi Pexel answers every one of these questions?\",\"cta_label\":\"Book a Discovery Call\"}]', 2, '2025-04-18')");

    $pdo->exec("INSERT IGNORE INTO blogs (title, slug, eyebrow, subtitle, excerpt, content, image_url, category, tags, author_name, author_role, read_time, status, sections, position, published_at) VALUES
('CRM-to-Campaign in 12 Days: The Automation Stack That Runs Your Outbound', 'crm-to-campaign-automation-stack', 'Growth Ops', 'How modern B2B teams wire HubSpot, LinkedIn, and AI into a single outbound engine', 'Stop running campaigns manually. Here is the exact automation stack that moves CRM signals into personalised outreach without touching a spreadsheet.', '', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800', 'Growth', 'CRM automation, HubSpot, outbound, sales ops, lead nurturing', 'Digi Pexel Team', 'Growth Automation Engineers', '9 min read', 'published', '[{\"id\":\"s1\",\"type\":\"overview\",\"title\":\"The Broken Outbound Loop Most Teams Are Running\",\"content\":\"The average B2B sales team manually exports CRM lists, pastes them into a sequencer, checks LinkedIn by hand, and reports pipeline in a deck built every Friday. This workflow is not just slow — it leaks leads at every step.\",\"points\":[\"Average CRM export to first outreach: 4.2 days\",\"40% of warm CRM leads never receive a follow-up within 24 hours\",\"Sales reps spend 2.5 hours per day on manual data tasks\"]},{\"id\":\"s2\",\"type\":\"challenge\",\"title\":\"The Stack: What You Need to Build It\",\"content\":\"You do not need to rip out your existing CRM. The automation layer sits on top of your current tools using webhook triggers, an n8n or Make orchestration layer, and an AI personalisation node.\",\"points\":[\"CRM: HubSpot or Salesforce with webhook support\",\"Orchestration: n8n Cloud or Make.com for workflow logic\",\"Personalisation: OpenAI API for context-aware message generation\",\"Delivery: LinkedIn via approved API or cold email via SMTP relay\",\"Reporting: Airtable or Google Sheets via API push\"]},{\"id\":\"s3\",\"type\":\"solution\",\"title\":\"The 12-Day Build Timeline\",\"content\":\"Day 1-3: Audit CRM hygiene and define trigger events. Day 4-6: Build orchestration layer and connect webhooks. Day 7-9: Train AI personalisation on your ICP messaging. Day 10-12: QA all branches, launch pilot with 50 contacts, monitor.\",\"points\":[\"Days 1-3: CRM audit and trigger event mapping\",\"Days 4-6: Orchestration layer build and webhook setup\",\"Days 7-9: AI personalisation training and sequence mapping\",\"Days 10-12: QA, pilot launch, and monitoring setup\"]},{\"id\":\"s4\",\"type\":\"metrics\",\"title\":\"What to Expect After 30 Days Live\",\"content\":\"Benchmarks from Digi Pexel clients running this stack.\",\"metrics\":[{\"value\":\"34%\",\"label\":\"Reply rate\",\"desc\":\"Up from 8% baseline\"},{\"value\":\"<2 hrs\",\"label\":\"CRM-to-outreach\",\"desc\":\"Down from 4+ days\"},{\"value\":\"2.8x\",\"label\":\"Pipeline volume\",\"desc\":\"Same team, same headcount\"},{\"value\":\"12 days\",\"label\":\"Deploy time\",\"desc\":\"From kickoff to live\"}]},{\"id\":\"s5\",\"type\":\"mid_cta\",\"cta_text\":\"Want this stack built for your team?\",\"cta_label\":\"Book a Build Call\"}]', 3, '2025-05-06')"  );

    // Seed case studies (INSERT IGNORE is idempotent — safe to re-run)
    $pdo->exec("INSERT IGNORE INTO case_studies (title, slug, eyebrow, subtitle, description, client_name, industry, image_url, hero_cta_label, hero_cta_url, hero_stats, sections, status, position, published_date) VALUES
('How FinFlows Automated 90% of Their Back-Office Operations', 'finflows-back-office-automation', 'Case Study', 'AI-powered workflow automation that eliminated manual processing and cut operational costs by 60%.', 'FinFlows, a fast-growing fintech platform, partnered with Digi Pexel to automate their loan processing, KYC verification, and monthly reporting pipelines.', 'FinFlows Inc.', 'Fintech', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', 'Start Your Project', '/contact-us', '[{\"label\":\"Ops Cost Reduction\",\"value\":\"60%\"},{\"label\":\"Processes Automated\",\"value\":\"40+\"},{\"label\":\"Hours Saved / Week\",\"value\":\"320h\"},{\"label\":\"ROI in 90 Days\",\"value\":\"4.2x\"}]', '[{\"id\":\"c1\",\"type\":\"challenge\",\"title\":\"The Problem: Manual Overload\",\"content\":\"The FinFlows ops team was spending 320 hours per week on manual loan processing, document verification, and compliance reporting. Error rates were high and the team could not scale without proportional headcount growth.\",\"points\":[\"48-hour average KYC verification time\",\"12% error rate on manual data entry\",\"Compliance reporting took 3 full-time employees\"]},{\"id\":\"c2\",\"type\":\"solution\",\"title\":\"The Approach: Autonomous Agent Stack\",\"content\":\"Digi Pexel designed a multi-agent automation system covering identity verification, document parsing, decision routing, and report generation — all orchestrated through a centralised workflow engine.\",\"points\":[\"Custom AI agent for document parsing and entity extraction\",\"Automated KYC decision routing with human escalation path\",\"Real-time compliance report generation via API integration\"]},{\"id\":\"c3\",\"type\":\"metrics\",\"title\":\"Results After 90 Days\",\"content\":\"Measured against pre-deployment baseline.\",\"metrics\":[{\"value\":\"60%\",\"label\":\"Ops cost reduction\",\"desc\":\"Year-one savings\"},{\"value\":\"4 hrs\",\"label\":\"KYC verification\",\"desc\":\"Down from 48 hours\"},{\"value\":\"99.1%\",\"label\":\"Data accuracy\",\"desc\":\"Up from 88%\"},{\"value\":\"4.2x\",\"label\":\"ROI\",\"desc\":\"Within 90 days\"}]}]', 'published', 0, '2025-03-14')");

    $pdo->exec("INSERT IGNORE INTO case_studies (title, slug, eyebrow, subtitle, description, client_name, industry, image_url, hero_cta_label, hero_cta_url, hero_stats, sections, status, position, published_date) VALUES
('How GrowthLoop Scaled LinkedIn Outreach 10x Without Hiring', 'growthloop-linkedin-scale', 'Case Study', 'AI-driven social selling automation that tripled qualified pipeline in 60 days.', 'GrowthLoop, a B2B SaaS company, needed to scale their outbound pipeline without expanding their SDR team. Digi Pexel built an autonomous LinkedIn prospecting and nurture system.', 'GrowthLoop', 'B2B SaaS', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80', 'Start Your Project', '/contact-us', '[{\"label\":\"Pipeline Growth\",\"value\":\"3x\"},{\"label\":\"SDR Hours Saved\",\"value\":\"120/wk\"},{\"label\":\"Response Rate\",\"value\":\"34%\"},{\"label\":\"Time to Deploy\",\"value\":\"3 wks\"}]', '[{\"id\":\"c1\",\"type\":\"challenge\",\"title\":\"The Problem: Outbound at a Ceiling\",\"content\":\"GrowthLoop had a skilled but overloaded SDR team spending 70% of their time on manual prospecting, personalisation, and follow-up. Conversion rates were flat despite headcount growth.\",\"points\":[\"SDRs spending 5+ hours daily on manual list building\",\"Inconsistent follow-up cadence losing warm leads\",\"Personalisation at scale impossible without automation\"]},{\"id\":\"c2\",\"type\":\"solution\",\"title\":\"The Approach: AI Social Selling Engine\",\"content\":\"We built an autonomous LinkedIn prospecting workflow combining AI-powered personalisation, smart sequencing, and intent-based prioritisation — all without violating platform terms.\",\"points\":[\"AI personalisation engine generating custom openers from profile data\",\"Intent-based prioritisation surfacing high-signal accounts daily\",\"Automated multi-touch sequences with human handoff triggers\"]},{\"id\":\"c3\",\"type\":\"metrics\",\"title\":\"Results After 60 Days\",\"content\":\"Measured against the 60-day pre-deployment baseline.\",\"metrics\":[{\"value\":\"3x\",\"label\":\"Qualified pipeline\",\"desc\":\"vs. prior period\"},{\"value\":\"34%\",\"label\":\"Response rate\",\"desc\":\"From 11% baseline\"},{\"value\":\"120 hrs\",\"label\":\"SDR time saved\",\"desc\":\"Per week across team\"},{\"value\":\"3 wks\",\"label\":\"Deployment time\",\"desc\":\"From kickoff to live\"}]}]', 'published', 1, '2025-04-10')");

    $pdo->exec("INSERT IGNORE INTO case_studies (title, slug, eyebrow, subtitle, description, client_name, industry, image_url, hero_cta_label, hero_cta_url, hero_stats, sections, status, position, published_date) VALUES
('How MediTrack Cut Patient Onboarding From 9 Days to 6 Hours', 'meditrack-patient-onboarding-automation', 'Case Study', 'AI-powered document intake and verification that eliminated manual processing across 4 clinic locations.', 'MediTrack, a multi-location healthcare SaaS provider, engaged Digi Pexel to automate their patient onboarding pipeline — reducing delays, eliminating manual data entry, and achieving near-instant eligibility checks.', 'MediTrack Health', 'Healthcare SaaS', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80', 'Start Your Project', '/contact-us', '[{\"label\":\"Onboarding Time\",\"value\":\"-93%\"},{\"label\":\"Manual Steps Eliminated\",\"value\":\"28\"},{\"label\":\"Staff Hours Saved/Wk\",\"value\":\"210h\"},{\"label\":\"Error Rate\",\"value\":\"0.3%\"}]', '[{\"id\":\"c1\",\"type\":\"challenge\",\"title\":\"The Problem: 9-Day Onboarding Backlog\",\"content\":\"MediTrack staff were spending 9 days on average processing each new patient: manually entering referral data from faxes and PDFs, checking insurance eligibility across 3 separate portals, and coordinating appointment scheduling via email threads.\",\"points\":[\"9-day average patient onboarding cycle\",\"4.2% data entry error rate causing claim rejections\",\"210 staff hours per week lost to manual intake tasks\"]},{\"id\":\"c2\",\"type\":\"solution\",\"title\":\"The Approach: Document AI + Eligibility Automation\",\"content\":\"Digi Pexel deployed a multi-stage AI pipeline that reads intake documents, extracts structured patient data, verifies insurance eligibility via API, and routes completed records directly into the EHR system — with a human checkpoint only for flagged edge cases.\",\"points\":[\"Document parsing agent extracting 40+ data fields from PDFs and images\",\"Real-time insurance eligibility verification via payer API integrations\",\"Automated EHR record creation with conflict-detection rules\",\"Human review queue for less than 3% of cases that trigger exception flags\"]},{\"id\":\"c3\",\"type\":\"metrics\",\"title\":\"Results After 60 Days Live\",\"content\":\"Measured against the 60-day pre-deployment baseline across all 4 clinic locations.\",\"metrics\":[{\"value\":\"6 hrs\",\"label\":\"Onboarding time\",\"desc\":\"Down from 9 days\"},{\"value\":\"0.3%\",\"label\":\"Data error rate\",\"desc\":\"Down from 4.2%\"},{\"value\":\"210 hrs\",\"label\":\"Staff time reclaimed\",\"desc\":\"Per week across locations\"},{\"value\":\"$340k\",\"label\":\"Annual cost saving\",\"desc\":\"Projected year-one\"}]}]', 'published', 2, '2025-04-28')");

    $pdo->exec("INSERT IGNORE INTO case_studies (title, slug, eyebrow, subtitle, description, client_name, industry, image_url, hero_cta_label, hero_cta_url, hero_stats, sections, status, position, published_date) VALUES
('How NexaRetail Automated Inventory Reporting and Saved 480 Ops Hours Monthly', 'nexaretail-inventory-reporting-automation', 'Case Study', 'Replacing weekly manual inventory reconciliation with a fully autonomous AI reporting pipeline.', 'NexaRetail, a fast-growing D2C brand operating across 3 fulfilment centres, partnered with Digi Pexel to automate their inventory reconciliation, stock alert, and supplier reorder workflows.', 'NexaRetail', 'E-Commerce / Retail', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', 'Start Your Project', '/contact-us', '[{\"label\":\"Ops Hours Saved/Mo\",\"value\":\"480h\"},{\"label\":\"Stockout Incidents\",\"value\":\"-78%\"},{\"label\":\"Report Accuracy\",\"value\":\"99.7%\"},{\"label\":\"Deployment Time\",\"value\":\"4 wks\"}]', '[{\"id\":\"c1\",\"type\":\"challenge\",\"title\":\"The Problem: 120-Hour Monthly Reconciliation Drain\",\"content\":\"NexaRetail operations managers were spending 120 hours every month manually reconciling inventory across three warehouse systems, two 3PL providers, and a Shopify storefront. Discrepancies were caught too late, causing frequent stockouts and oversells.\",\"points\":[\"120 hours/month on manual inventory reconciliation\",\"Average 3-day lag between stockout and reorder trigger\",\"18% of weekly reports contained at least one material error\"]},{\"id\":\"c2\",\"type\":\"solution\",\"title\":\"The Approach: Unified Inventory Intelligence Layer\",\"content\":\"Digi Pexel built an automation layer that pulls live inventory data from all warehouse and commerce systems, reconciles discrepancies using rule-based logic, generates daily exception reports, and triggers supplier reorder emails autonomously when par levels are breached.\",\"points\":[\"Unified API sync across Shopify, WMS, and 3PL portals every 4 hours\",\"AI reconciliation engine flagging discrepancies within 15 minutes of detection\",\"Automated supplier reorder emails with PO draft generation\",\"Daily and weekly summary dashboards emailed to leadership at 7am\"]},{\"id\":\"c3\",\"type\":\"metrics\",\"title\":\"Results After 30 Days Live\",\"content\":\"Measured against the 30-day pre-deployment baseline.\",\"metrics\":[{\"value\":\"480 hrs\",\"label\":\"Ops time saved\",\"desc\":\"Per month total\"},{\"value\":\"-78%\",\"label\":\"Stockout incidents\",\"desc\":\"vs. prior 30 days\"},{\"value\":\"99.7%\",\"label\":\"Report accuracy\",\"desc\":\"Up from 82%\"},{\"value\":\"4 wks\",\"label\":\"Time to deploy\",\"desc\":\"Kickoff to full automation\"}]}]', 'published', 3, '2025-05-09')");

    // Migrate guide slugs if previously seeded with old slugs
    $pdo->exec("UPDATE guides SET slug = 'ai-automation-roadmap-12-month-playbook' WHERE slug = 'ai-automation-roadmap-12-month'");
    $pdo->exec("UPDATE guides SET slug = 'geo-vs-seo-complete-guide' WHERE slug = 'geo-vs-seo-ai-citation-guide'");

    // Seed guides (INSERT IGNORE is idempotent — safe to re-run)
    $pdo->exec("INSERT IGNORE INTO guides (title, slug, description, content, image_url, category, cta_label, cta_link, position) VALUES
('The AI Automation Roadmap: A 12-Month Playbook for B2B Teams', 'ai-automation-roadmap-12-month-playbook', 'A step-by-step framework for auditing your operations, identifying high-ROI automation opportunities, and building a deployment plan that delivers measurable results within 90 days.', '<h2>Why Most Automation Projects Fail Before They Start</h2><p>Without a clear audit methodology, companies automate the wrong things first — spending budget on low-impact workflows while high-value bottlenecks remain manual. This playbook gives you the framework to avoid that mistake.</p><h2>Phase 1: The Operations Audit (Weeks 1-2)</h2><p>Start by mapping every workflow that involves more than 3 manual steps. Score each workflow on two dimensions: time cost per week and strategic impact. Automate high time-cost, high-impact workflows first.</p><h2>Phase 2: Tool Selection (Weeks 3-4)</h2><p>Match your workflow complexity to the right automation platform. Simple linear flows work well in Zapier or Make. Complex conditional logic with AI decision layers needs n8n or a custom agent framework.</p><h2>Phase 3: Build and Test (Weeks 5-10)</h2><p>Build one workflow at a time. Each workflow must have: a defined trigger, a logic layer, error handling with alerts, and an observable output. Do not move to the next workflow until the current one is stable for 2 weeks.</p><h2>Phase 4: Scale and Optimise (Weeks 11-12)</h2><p>Once your first batch of workflows are stable, introduce monitoring dashboards, set KPI targets, and begin the second round of automation based on updated audit data.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800', 'Strategy', 'Read the Playbook', '#', 0)");

    $pdo->exec("INSERT IGNORE INTO guides (title, slug, description, content, image_url, category, cta_label, cta_link, position) VALUES
('GEO vs SEO: The Complete Guide to Getting Your Brand Cited by AI', 'geo-vs-seo-complete-guide', 'Everything B2B marketing leaders need to know about Generative Engine Optimisation — how AI assistants select citations, what signals matter, and how to build a content strategy that wins in the AI answer era.', '<h2>The Search Landscape Has Changed</h2><p>When a buyer asks ChatGPT or Perplexity about the best automation agency, they receive a direct answer with 3-5 citations. If your brand is not cited, you do not exist in that decision. GEO is the discipline of ensuring you are always one of those citations.</p><h2>How AI Assistants Choose Citations</h2><p>LLMs are trained on web content and augmented with real-time retrieval. They prioritise: authoritative domains with strong topical depth, content that directly answers the query intent, structured markup that makes facts machine-readable, and content cited or linked to by other authoritative sources.</p><h2>The GEO Content Framework</h2><p>Step 1: Build entity authority. Create comprehensive topic clusters around your core service areas. Step 2: Use structured data markup (FAQ, HowTo, Article schemas). Step 3: Publish original research and data — LLMs cite statistics heavily. Step 4: Earn editorial citations from industry publications. Step 5: Monitor your citation rate using AI search tools quarterly.</p><h2>Measuring GEO Success</h2><p>Track: Brand mention rate in AI assistants (test manually monthly), citation share vs. competitors, and inbound traffic from AI-assisted research sessions (identifiable in GA4 by referral source patterns).</p>', 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800', 'SEO', 'Read the Guide', '#', 1)");

    $pdo->exec("INSERT IGNORE INTO guides (title, slug, description, content, image_url, category, cta_label, cta_link, position) VALUES
('The AI Vendor Selection Scorecard: 7 Criteria Every Ops Leader Must Evaluate', 'ai-vendor-selection-scorecard', 'A structured evaluation framework for B2B operations leaders vetting AI automation partners. Score vendors across 7 weighted criteria and make a confident, data-backed selection decision.', '<h2>Why Vendor Selection Is the Highest-Stakes Decision in Your AI Journey</h2><p>Once you commit to an AI automation vendor, switching costs are high — your data, workflows, and team training are all tied to their platform. Getting the selection right the first time is worth slowing down to evaluate properly.</p><h2>The 7 Criteria Framework</h2><p><strong>1. Production Track Record (25 pts):</strong> Has the vendor deployed automations of similar complexity to yours in production — not demos, not pilots? Ask for 3 client references in your industry and call them.<br/><strong>2. Observability and Monitoring (20 pts):</strong> How do they detect, alert, and resolve failures in production workflows? Any serious vendor has real-time monitoring and defined SLAs.<br/><strong>3. Security and Data Governance (20 pts):</strong> Where is your data processed? Who has access? Can they provide a data processing agreement and SOC 2 documentation?<br/><strong>4. Integration Depth (15 pts):</strong> Do they have native integrations with your core stack (CRM, ERP, HRIS) or will everything require custom API work? Custom work = higher cost and longer timelines.<br/><strong>5. Team and Account Model (10 pts):</strong> Who will own your day-to-day relationship? What is the escalation path? Avoid vendors where your account manager is also the engineer.<br/><strong>6. Pricing Transparency (5 pts):</strong> Are costs fixed-scope or hourly? Are there hidden costs for infrastructure, API calls, or support tickets?<br/><strong>7. Exit and Portability (5 pts):</strong> If you leave, do you own all workflows and credentials? Is your automation logic locked into a proprietary platform?</p><h2>How to Score and Decide</h2><p>Score each vendor 1-5 on every criterion, then multiply by the weight. A score above 80/100 is a strong selection. Any criterion scored 1 should be treated as a disqualifier regardless of the total score.</p>', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800', 'Strategy', 'Download the Scorecard', '#', 2)");

    $pdo->exec("INSERT IGNORE INTO guides (title, slug, description, content, image_url, category, cta_label, cta_link, position) VALUES
('The 90-Day Ops Transformation Playbook: From Manual to Automated', '90-day-ops-transformation-playbook', 'A week-by-week implementation guide for founders and COOs who want to automate their core operations without disrupting the business. Covers audit methodology, tool selection, build sprints, and go-live validation.', '<h2>Why 90 Days Is the Right Horizon</h2><p>Automation projects that try to do everything at once fail. Projects that are too narrowly scoped deliver marginal value. 90 days is long enough to automate 3-5 high-impact workflows and short enough to maintain executive sponsorship and team momentum.</p><h2>Month 1: The Audit (Weeks 1-4)</h2><p>Week 1-2: Map every operational workflow that touches more than 3 people or takes more than 4 hours per week. Create a simple spreadsheet with: workflow name, time cost per week, error rate, and strategic impact score (1-5).<br/>Week 3-4: Score workflows on an automation feasibility matrix. High time cost + high strategic impact + structured data = automate first. Low feasibility + low impact = skip entirely. Deliver an Automation Priority Report to leadership before Month 2 begins.</p><h2>Month 2: The Build (Weeks 5-10)</h2><p>Week 5-6: Select your tool stack based on workflow complexity. Simple linear flows: Zapier or Make. Complex conditional logic with AI: n8n or custom agent. Week 7-10: Build workflows in order of priority. Each workflow needs: trigger definition, logic layer, error handling with alerts, a test suite with 20+ edge cases, and a defined human escalation path. Do not move to the next workflow until the current one passes QA for 5 consecutive test runs.</p><h2>Month 3: Launch and Validate (Weeks 11-12)</h2><p>Week 11: Soft launch with real data on a shadow pipeline. Compare automated outputs against manual baseline for 5 business days. Week 12: Full go-live. Set KPI targets (time saved, error rate, throughput). Schedule a 30-day and 60-day performance review with leadership. Build a monitoring dashboard that surfaces anomalies before they escalate.</p>', 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&q=80&w=800', 'Operations', 'Read the Playbook', '#', 3)"  );

    // Seed default settings
    $pdo->exec("INSERT INTO settings (`key`, `value`) SELECT 'whatsapp_number', '' WHERE NOT EXISTS (SELECT 1 FROM settings WHERE `key` = 'whatsapp_number')");
    // Always ensure whatsapp_enabled is "true" — button must never be hidden by a stale DB row
    $pdo->exec("INSERT INTO settings (`key`, `value`) VALUES ('whatsapp_enabled', 'true') ON DUPLICATE KEY UPDATE `value` = 'true'");

    // Seed site_content sections (ON DUPLICATE KEY UPDATE so values stay current on re-runs)
    $pdo->exec("INSERT INTO site_content (section, content) VALUES ('stats', '{\"stats\":[{\"label\":\"FASTER SHIPPING\",\"value\":\"42%\",\"description\":\"Automation eliminates handoffs and approvals so teams ship at the speed of AI.\"},{\"label\":\"LOWER OPS COST\",\"value\":\"28%\",\"description\":\"Saved on run-rate by removing manual steps, rework, and duplicate tooling.\"},{\"label\":\"HOURS RECOVERED\",\"value\":\"12k+\",\"description\":\"Returned to teams by automating data movement, follow-ups, and reporting.\"},{\"label\":\"TIME TO DEPLOY\",\"value\":\"4-6 wks\",\"description\":\"From discovery to production workflows with full monitoring and governance.\"}]}') ON DUPLICATE KEY UPDATE content = VALUES(content)");
    $pdo->exec("INSERT INTO site_content (section, content) VALUES ('problem', '{\"stat1_value\":\"14 hrs\",\"stat1_detail\":\"lost per team / week\",\"stat1_title\":\"Handoff Friction\",\"stat1_body\":\"Every tool switch and status update burns hours that should go toward delivering real outcomes.\",\"stat2_value\":\"6+ tools\",\"stat2_detail\":\"disconnected on average\",\"stat2_title\":\"Siloed Systems\",\"stat2_body\":\"Fragmented data means your AI can\'t see the full picture — so the right action never gets triggered.\",\"stat3_value\":\"40%\",\"stat3_detail\":\"of all work is rework\",\"stat3_title\":\"Manual Rework\",\"stat3_body\":\"Teams spend nearly half their time re-entering or reformatting information that already exists somewhere else.\"}') ON DUPLICATE KEY UPDATE content = VALUES(content)");

    // ── service_content seed (INSERT IGNORE so re-runs never overwrite admin edits) ──

    // ai-seo
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'hero', '{\"badge\":\"AI SEO Automation\",\"heroLine1\":\"Stop optimizing for bots.\",\"heroLine2\":\"Start winning AI answers.\",\"heroCopy\":\"We build AI-ready content systems that make your brand the default citation across search assistants, copilots, and LLM-driven research.\",\"ctaPrimary\":\"Book a Strategy Call\",\"pills\":[\"GEO Strategy\",\"Entity Authority\",\"RAG Readiness\"],\"snapshotTitle\":\"Live Visibility Snapshot\",\"snapshotRows\":[\"Model citations: 68%\",\"Entity coverage: 92%\",\"Prompt intent match: 84%\",\"Trust signals: 76%\"],\"statLabel1\":\"Visibility Delta\",\"statValue1\":\"+41%\",\"statLabel2\":\"AI Answer Rate\",\"statValue2\":\"3.2x\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'features', '{\"cards\":[{\"title\":\"GEO Optimization\",\"description\":\"Optimize for Generative Engine Results to ensure your brand is cited by LLMs.\"},{\"title\":\"Entity Authority\",\"description\":\"Map your content to semantic entities to build topical authority that AI understands.\"},{\"title\":\"Automated Content Loop\",\"description\":\"A system that continuously updates content based on AI search trends and intent.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-seo', 'testimonials', '{\"items\":[{\"quote\":\"Our brand citations in Perplexity and ChatGPT increased by 140% in just two months.\",\"role\":\"CEO\",\"company\":\"Nexus Tech\"},{\"quote\":\"The zero-click search visibility we\'ve gained has been a game-changer for our organic traffic.\",\"role\":\"Marketing Director\",\"company\":\"Aura Media\"}]}')");

    // custom-ai-solutions
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'hero', '{\"badge\":\"Custom AI Solutions\",\"heroLine1\":\"Build AI that fits\",\"heroLine2\":\"your business logic.\",\"heroCopy\":\"We design bespoke AI solutions that integrate with your data, workflows, and proprietary processes. From copilots to autonomous systems, we make AI operational.\",\"ctaPrimary\":\"Plan a Discovery Call\",\"pills\":[\"AI Architecture\",\"Data Pipelines\",\"Workflow Integration\"],\"snapshotTitle\":\"Solution Readiness\",\"snapshotRows\":[\"Use-case clarity: 88%\",\"Data availability: 79%\",\"Model fit score: 86%\",\"Security readiness: 82%\"],\"statLabel1\":\"Delivery speed\",\"statValue1\":\"3x\",\"statLabel2\":\"Ops uplift\",\"statValue2\":\"+45%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'features', '{\"cards\":[{\"title\":\"Custom Agent Design\",\"description\":\"Build autonomous agents specialized in your unique business operations.\"},{\"title\":\"Proprietary RAG\",\"description\":\"Securely connect your private data to LLMs for accurate, context-aware answers.\"},{\"title\":\"Legacy Integration\",\"description\":\"Seamlessly bridge modern AI capabilities with your existing software stack.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('custom-ai-solutions', 'testimonials', '{\"items\":[{\"quote\":\"Digi Pexel built a custom RAG system that cut our document analysis time from hours to seconds.\",\"role\":\"Head of Operations\",\"company\":\"Fortress Law\"},{\"quote\":\"Our proprietary AI agent now handles 80% of our initial client intake with perfect accuracy.\",\"role\":\"Founder\",\"company\":\"ScaleUp\"}]}')");

    // youtube-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'hero', '{\"badge\":\"YouTube Automation\",\"heroLine1\":\"Scale your channel\",\"heroLine2\":\"without the bottlenecks.\",\"heroCopy\":\"We automate scripting, production coordination, publishing, and analytics so your YouTube engine runs every week without burnout.\",\"ctaPrimary\":\"Audit My Channel\",\"pills\":[\"Content Engine\",\"Publishing Ops\",\"Audience Growth\"],\"snapshotTitle\":\"Channel Momentum\",\"snapshotRows\":[\"Upload consistency: 92%\",\"Retention lift: +28%\",\"Topic velocity: 3.4x\",\"Revenue mix: 47%\"],\"statLabel1\":\"Time saved\",\"statValue1\":\"12 hrs/wk\",\"statLabel2\":\"Output lift\",\"statValue2\":\"3x\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'features', '{\"cards\":[{\"title\":\"AI Scripting Engine\",\"description\":\"Generate data-backed scripts that maximize viewer retention and engagement.\"},{\"title\":\"Production Pipeline\",\"description\":\"Automated coordination between editors, designers, and upload managers.\"},{\"title\":\"Topic Velocity\",\"description\":\"Rapidly identify and execute on trending topics before the competition.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('youtube-automation', 'testimonials', '{\"items\":[{\"quote\":\"Closing 8 channels a week used to be impossible. Now we do 12 with a smaller team.\",\"role\":\"Channel Manager\",\"company\":\"MediaFlow\"},{\"quote\":\"The AI scripting tool understands our audience better than we did. Retention is up 35%.\",\"role\":\"Creative Director\",\"company\":\"TubeFoundry\"}]}')");

    // instagram-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'hero', '{\"badge\":\"Instagram Automation\",\"heroLine1\":\"Grow consistently\",\"heroLine2\":\"without manual grind.\",\"heroCopy\":\"Automate content scheduling, engagement workflows, and performance tracking so your brand stays always-on and on-strategy.\",\"ctaPrimary\":\"Get an IG Audit\",\"pills\":[\"Content System\",\"Engagement Ops\",\"Brand Voice\"],\"snapshotTitle\":\"Social Pulse\",\"snapshotRows\":[\"Posting rhythm: 90%\",\"Engagement rate: +22%\",\"DM response time: 3h\",\"Content reuse: 2.6x\"],\"statLabel1\":\"Engagement lift\",\"statValue1\":\"+22%\",\"statLabel2\":\"Time saved\",\"statValue2\":\"9 hrs/wk\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'features', '{\"cards\":[{\"title\":\"Engagement Automator\",\"description\":\"AI-powered DM and comment handling that maintains authentic brand voice.\"},{\"title\":\"Visual Content Hub\",\"description\":\"Centralized system for generating and scheduling Reels, Carousels, and Stories.\"},{\"title\":\"Pattern Analysis\",\"description\":\"Automatically identify what content drives the most follows and sales.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('instagram-automation', 'testimonials', '{\"items\":[{\"quote\":\"Our engagement rate spiked 25% after automating our DM triage system.\",\"role\":\"Social Lead\",\"company\":\"Vibe Marketing\"},{\"quote\":\"We finally have an always-on presence without hiring 3 more community managers.\",\"role\":\"Founder\",\"company\":\"GlowUp\"}]}')");

    // linkedin-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'hero', '{\"badge\":\"LinkedIn Automation\",\"heroLine1\":\"Build authority\",\"heroLine2\":\"at scale.\",\"heroCopy\":\"We automate content publishing, audience engagement, and lead capture so your LinkedIn presence drives pipeline consistently.\",\"ctaPrimary\":\"Book a LinkedIn Audit\",\"pills\":[\"Authority Building\",\"Outbound Assist\",\"Lead Capture\"],\"snapshotTitle\":\"Authority Scorecard\",\"snapshotRows\":[\"Post cadence: 4x\",\"Profile views: +58%\",\"Inbound leads: +36%\",\"Engagement rate: 6.1%\"],\"statLabel1\":\"Lead lift\",\"statValue1\":\"+36%\",\"statLabel2\":\"Authority growth\",\"statValue2\":\"+58%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'features', '{\"cards\":[{\"title\":\"Thought Leadership Ops\",\"description\":\"Scale your professional voice with AI-assisted post generation and scheduling.\"},{\"title\":\"Social Selling Flows\",\"description\":\"Automated lead nurturing and profile visit follow-ups that feel personal.\"},{\"title\":\"Network Growth\",\"description\":\"Strategic connection automation to build a highly targeted industry network.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('linkedin-automation', 'testimonials', '{\"items\":[{\"quote\":\"My LinkedIn profile views went from 200 to 5,000 a week. The authority we\'ve built is massive.\",\"role\":\"B2B Founder\",\"company\":\"SaaS Rocket\"},{\"quote\":\"The outreach automation is so subtle—nobody knows it\'s a system, but the results are very real.\",\"role\":\"Sales Director\",\"company\":\"Prime Edge\"}]}')");

    // automation-flows
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'hero', '{\"badge\":\"Automation Flows\",\"heroLine1\":\"Connect your stack\",\"heroLine2\":\"without friction.\",\"heroCopy\":\"We build automation flows that move data and actions across your tools with reliability, observability, and scale.\",\"ctaPrimary\":\"Map My Workflows\",\"pills\":[\"System Orchestration\",\"Data Sync\",\"Reliability\"],\"snapshotTitle\":\"Workflow Health\",\"snapshotRows\":[\"Success rate: 99.2%\",\"Latency: 1.8s\",\"Manual touches: -64%\",\"Error recovery: 92%\"],\"statLabel1\":\"Ops time saved\",\"statValue1\":\"-64%\",\"statLabel2\":\"Flow uptime\",\"statValue2\":\"99.2%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'features', '{\"cards\":[{\"title\":\"Event Orchestration\",\"description\":\"Build complex multi-step flows that trigger based on specific data events.\"},{\"title\":\"Data Synchronization\",\"description\":\"Keep your entire tech stack in sync with zero-latency data transfers.\"},{\"title\":\"Observability Hub\",\"description\":\"Real-time monitoring and alerting for every automated process you run.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('automation-flows', 'testimonials', '{\"items\":[{\"quote\":\"Our data syncing issues used to cost us $10k a month. Now everything is perfectly in sync.\",\"role\":\"CTO\",\"company\":\"DataFirst\"},{\"quote\":\"The observability dashboards give us total peace of mind for our critical business flows.\",\"role\":\"IT Manager\",\"company\":\"SwiftCore\"}]}')");

    // ai-workflows
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'hero', '{\"badge\":\"AI Workflows\",\"heroLine1\":\"Let AI run\",\"heroLine2\":\"the complex decisions.\",\"heroCopy\":\"We build AI workflows that chain decisions, approvals, and actions across your business with auditability and control.\",\"ctaPrimary\":\"Design My Workflow\",\"pills\":[\"Decision Chains\",\"Human-in-Loop\",\"24/7 Ops\"],\"snapshotTitle\":\"Workflow Intelligence\",\"snapshotRows\":[\"Decision accuracy: 93%\",\"Escalation rate: 7%\",\"Automation coverage: 68%\",\"Cycle time: -41%\"],\"statLabel1\":\"Cycle time\",\"statValue1\":\"-41%\",\"statLabel2\":\"Decision accuracy\",\"statValue2\":\"93%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'features', '{\"cards\":[{\"title\":\"Decision Intelligence\",\"description\":\"AI that reasons through complex scenarios and takes the right action.\"},{\"title\":\"Human-in-Loop QA\",\"description\":\"Smart checkpoints that escalate complex cases to humans while automating the rest.\"},{\"title\":\"Context Chain\",\"description\":\"Maintain business context across multiple automation steps for smarter outcomes.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('ai-workflows', 'testimonials', '{\"items\":[{\"quote\":\"The AI decision chains now handle 70% of our complex claims approvals.\",\"role\":\"Operations Director\",\"company\":\"InsurePlus\"},{\"quote\":\"Bridging human insight with AI reasoning has halved our processing time.\",\"role\":\"Process Architect\",\"company\":\"LogiNext\"}]}')");

    // workflow-creation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'hero', '{\"badge\":\"Workflow Creation\",\"heroLine1\":\"Architect workflows\",\"heroLine2\":\"that never break.\",\"heroCopy\":\"We design dependable business workflows with clear ownership, automation hooks, and measurable performance.\",\"ctaPrimary\":\"Build My Workflow\",\"pills\":[\"Process Design\",\"Automation Ready\",\"Reliability\"],\"snapshotTitle\":\"Workflow Readiness\",\"snapshotRows\":[\"Process clarity: 88%\",\"Automation fit: 74%\",\"Error rate: 6%\",\"Cycle time: -32%\"],\"statLabel1\":\"Cycle time\",\"statValue1\":\"-32%\",\"statLabel2\":\"Automation fit\",\"statValue2\":\"74%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'features', '{\"cards\":[{\"title\":\"System Mapping\",\"description\":\"Detailed blueprints of your business operations to identify automation points.\"},{\"title\":\"Performance Benchmarking\",\"description\":\"Measure every step of your workflow to find and fix hidden bottlenecks.\"},{\"title\":\"Fail-safe Design\",\"description\":\"Workflows built with built-in redundancies and error handling protocols.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('workflow-creation', 'testimonials', '{\"items\":[{\"quote\":\"The blueprints Digi Pexel mapped out revealed bottlenecks we never knew existed.\",\"role\":\"COO\",\"company\":\"Atlas Studio\"},{\"quote\":\"We finally have a scalable workflow architecture that doesn\'t break under pressure.\",\"role\":\"Founder\",\"company\":\"LaunchPoint\"}]}')");

    // accounting-bookkeeping
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'hero', '{\"badge\":\"Accounting Automation\",\"heroLine1\":\"Close books faster\",\"heroLine2\":\"with zero-touch workflows.\",\"heroCopy\":\"We automate reconciliation, reporting, and financial workflows so your team focuses on analysis, not manual cleanup.\",\"ctaPrimary\":\"Book an Accounting Audit\",\"pills\":[\"Reconciliation\",\"Reporting\",\"Compliance\"],\"snapshotTitle\":\"Finance Health\",\"snapshotRows\":[\"Close time: -40%\",\"Reconciliation accuracy: 99%\",\"AP cycle time: -32%\",\"Manual entries: -70%\"],\"statLabel1\":\"Close time\",\"statValue1\":\"-40%\",\"statLabel2\":\"Manual entries\",\"statValue2\":\"-70%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'features', '{\"cards\":[{\"title\":\"Zero-touch Reconciliation\",\"description\":\"Automatically match bank statements with your ledger using AI pattern recognition.\"},{\"title\":\"Real-time P&L\",\"description\":\"Live financial dashboards that update instantly as transactions occur.\"},{\"title\":\"Compliance Guard\",\"description\":\"Automated audits that flag inconsistencies and ensure tax readiness year-round.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('accounting-bookkeeping', 'testimonials', '{\"items\":[{\"quote\":\"Closing our month-end now takes 3 days instead of 12. Total transformation.\",\"role\":\"CFO\",\"company\":\"Global Ledger\"},{\"quote\":\"The accuracy and speed of our automated reconciliation is beyond what we expected.\",\"role\":\"Controller\",\"company\":\"FinPath\"}]}')");

    // hiring-recruitment
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'hero', '{\"badge\":\"Hiring Automation\",\"heroLine1\":\"Hire faster\",\"heroLine2\":\"with AI-driven pipelines.\",\"heroCopy\":\"We automate sourcing, screening, and outreach to help you scale hiring without sacrificing quality.\",\"ctaPrimary\":\"Audit My Hiring Flow\",\"pills\":[\"Sourcing\",\"Screening\",\"Candidate Experience\"],\"snapshotTitle\":\"Hiring Velocity\",\"snapshotRows\":[\"Time-to-hire: -35%\",\"Qualified applicants: +48%\",\"Response time: 2h\",\"Offer acceptance: 82%\"],\"statLabel1\":\"Time-to-hire\",\"statValue1\":\"-35%\",\"statLabel2\":\"Qualified leads\",\"statValue2\":\"+48%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'features', '{\"cards\":[{\"title\":\"AI Candidate Sourcing\",\"description\":\"Find top talent across platforms automatically with intelligent search agents.\"},{\"title\":\"Automated Screening\",\"description\":\"Smart interviews and skill assessments that filter for quality at scale.\"},{\"title\":\"Engagement Engine\",\"description\":\"Personalized candidate outreach that maintains high response rates.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('hiring-recruitment', 'testimonials', '{\"items\":[{\"quote\":\"Our cost-per-hire dropped 40% while our candidate quality actually improved.\",\"role\":\"HR Director\",\"company\":\"ScaleRecruit\"},{\"quote\":\"The AI screening process has saved our team hundreds of hours in top-of-funnel work.\",\"role\":\"Talent Lead\",\"company\":\"Innovate Hub\"}]}')");

    // sales-automation
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'hero', '{\"badge\":\"Sales Automation\",\"heroLine1\":\"Convert faster\",\"heroLine2\":\"with automated follow-up.\",\"heroCopy\":\"We automate lead scoring, nurturing, and pipeline hygiene so sales teams focus on closing, not chasing.\",\"ctaPrimary\":\"Audit My Sales Ops\",\"pills\":[\"Lead Scoring\",\"Follow-up\",\"Pipeline Hygiene\"],\"snapshotTitle\":\"Pipeline Health\",\"snapshotRows\":[\"Response time: -45%\",\"Conversion lift: +29%\",\"Lead scoring: 94%\",\"Stale deals: -38%\"],\"statLabel1\":\"Conversion lift\",\"statValue1\":\"+29%\",\"statLabel2\":\"Response time\",\"statValue2\":\"-45%\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'features', '{\"cards\":[{\"title\":\"Predictive Lead Scoring\",\"description\":\"AI that identifies your highest-value leads before you even contact them.\"},{\"title\":\"Multi-channel Follow-up\",\"description\":\"Automated nurturing across Email, LinkedIn, and SMS that never misses a beat.\"},{\"title\":\"CRM Hygiene Bots\",\"description\":\"Autonomous agents that keep your sales data accurate and pipeline clean.\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'roadmap', '{\"roadmapTitle\":\"The 6-step delivery\",\"roadmapTitleAccent\":\"roadmap\",\"roadmapCopy\":\"A transparent, milestone-driven approach to moving from manual friction to autonomous excellence.\",\"items\":[{\"step\":\"01\",\"title\":\"Discovery\",\"desc\":\"Process auditing & feasibility\"},{\"step\":\"02\",\"title\":\"Architecture\",\"desc\":\"Logic mapping & tool selection\"},{\"step\":\"03\",\"title\":\"Engineering\",\"desc\":\"Build & data integration\"},{\"step\":\"04\",\"title\":\"Validation\",\"desc\":\"Security audit & QA testing\"},{\"step\":\"05\",\"title\":\"Deployment\",\"desc\":\"Live launch & pilot monitoring\"},{\"step\":\"06\",\"title\":\"Scale\",\"desc\":\"Performance tuning & expansion\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'market_impact', '{\"outcomesTitle\":\"Partnering for\",\"outcomesTitleAccent\":\"high-velocity growth\",\"outcomesCopy\":\"We help modern teams ship faster without increasing headcount or complexity.\",\"cards\":[{\"quote\":\"We removed the manual bottlenecks and shipped weekly.\",\"company\":\"Atlas Studio\",\"sector\":\"Operations\",\"metricValue\":\"2x\",\"metricLabel\":\"Throughput\"},{\"quote\":\"Quality improved while cycle time dropped.\",\"company\":\"Signal Ops\",\"sector\":\"Delivery\",\"metricValue\":\"-38%\",\"metricLabel\":\"Cycle time\"}],\"stats\":[{\"value\":\"2x\",\"label\":\"Throughput\"},{\"value\":\"38%\",\"label\":\"Faster cycles\"},{\"value\":\"6\",\"label\":\"Weeks to launch\"},{\"value\":\"24/7\",\"label\":\"Monitoring\"}]}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'cta', '{\"ctaBadge\":\"Deployment Ready\",\"ctaTitle\":\"Ship faster with automation.\",\"ctaCopy\":\"Get a tailored plan and deployment timeline in days, not weeks. Start building your autonomous future today.\"}')");
    $pdo->exec("INSERT IGNORE INTO service_content (slug, section, content) VALUES ('sales-automation', 'testimonials', '{\"items\":[{\"quote\":\"Our sales reps are spending 90% of their time on hot leads now. Conversion is at an all-time high.\",\"role\":\"VP Sales\",\"company\":\"CloudScale\"},{\"quote\":\"Automating our follow-up sequences has ensured no lead ever falls through the cracks again.\",\"role\":\"Founder\",\"company\":\"Apex Systems\"}]}')");

    echo "Database initialized successfully.";
} catch (PDOException $e) {
    die("DB Init Error: " . $e->getMessage());
}
